[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.5.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[[bin]]
name = "kernel"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
